[project]
name = "inkline"

[env]
development = ".env"

[up]
steps = [

]

[down]
steps = [

]

[start]
commands = [
	"npm start"
]

[tasks]
publish = "npm run publish"

[open]
repo = "https://github.com/enxilium/inkline"
website = "https://inkline.jacemu.xyz/"
