import "dotenv/config";
import {
    app,
    BrowserWindow,
    dialog,
    ipcMain,
    Menu,
    MenuItemConstructorOptions,
    protocol,
    net,
    shell,
} from "electron";
import { updateElectronApp } from "update-electron-app";
import { spawn } from "child_process";
import fs from "fs";
import * as path from "path";
import { pathToFileURL } from "url";
import { AppBuilder } from "./AppBuilder";
import { resolveDependencies } from "./dependencies";
import { fileSystemService } from "../@infrastructure/storage/FileSystemService";
import { setupService } from "../@infrastructure/services/SetupService";
import {
    modelDownloadService,
    DownloadProgress,
} from "../@infrastructure/services/ModelDownloadService";
import { languageToolService } from "../@infrastructure/services/LanguageToolService";
import {
    createTerminalLogger,
    installTerminalErrorRedirection,
} from "../@infrastructure/services/TerminalLogger";
import {
    SETUP_CHANNELS,
    FEATURE_CHANNELS,
} from "../@interface-adapters/controllers/setup/setupChannels";
import type { FeatureKind } from "../@interface-adapters/controllers/setup/setupChannels";
import type { StartupIntegrityStatus } from "../@interface-adapters/controllers/setup/setupChannels";

const logger = createTerminalLogger("Main");
installTerminalErrorRedirection("Console");

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const LOADING_WINDOW_WEBPACK_ENTRY: string;
declare const LOADING_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const SETUP_WINDOW_WEBPACK_ENTRY: string;
declare const SETUP_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle Squirrel events for Windows installer (install/uninstall/update)
const handleSquirrelEvent = (): boolean => {
    if (process.platform !== "win32") {
        return false;
    }

    const squirrelCommand = process.argv[1];
    if (!squirrelCommand) {
        return false;
    }

    const appFolder = path.resolve(process.execPath, "..");
    const rootFolder = path.resolve(appFolder, "..");
    const updateExe = path.resolve(rootFolder, "Update.exe");
    const exeName = path.basename(process.execPath);

    const spawnUpdate = (args: string[]) => {
        try {
            spawn(updateExe, args, { detached: true });
        } catch {
            // Ignore spawn errors
        }
    };

    // Squirrel passes version as argument: --squirrel-uninstall 1.0.0
    if (
        squirrelCommand === "--squirrel-install" ||
        squirrelCommand === "--squirrel-updated"
    ) {
        // Create shortcuts
        spawnUpdate(["--createShortcut", exeName]);
        setTimeout(() => app.quit(), 1000);
        return true;
    }

    if (squirrelCommand === "--squirrel-uninstall") {
        // Remove shortcuts
        spawnUpdate(["--removeShortcut", exeName]);

        // Clean up downloaded AI files and user data
        try {
            const userDataPath = app.getPath("userData");
            const serverPath = path.join(process.resourcesPath || "", "server");

            // Delete setup config
            const configPath = path.join(userDataPath, "inkline-setup.json");
            if (fs.existsSync(configPath)) {
                fs.unlinkSync(configPath);
                logger.success("[Uninstall] Removed setup config");
            }

            // Delete server directory (contains ComfyUI, models, LanguageTool)
            if (fs.existsSync(serverPath)) {
                fs.rmSync(serverPath, { recursive: true, force: true });
                logger.success("[Uninstall] Removed server directory");
            }

            // Delete any cached data in userData
            const cachePaths = ["Cache", "GPUCache", "logs"];
            for (const cachePath of cachePaths) {
                const fullPath = path.join(userDataPath, cachePath);
                if (fs.existsSync(fullPath)) {
                    fs.rmSync(fullPath, { recursive: true, force: true });
                }
            }
            logger.success("[Uninstall] Cleanup complete");
        } catch (err) {
            logger.error("[Uninstall] Cleanup error", err);
        }

        setTimeout(() => app.quit(), 1000);
        return true;
    }

    if (squirrelCommand === "--squirrel-obsolete") {
        app.quit();
        return true;
    }

    return false;
};

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (handleSquirrelEvent()) {
    // Squirrel event handled, don't continue with normal startup
} else if (require("electron-squirrel-startup")) {
    app.quit();
}

// Register custom protocol scheme for serving local assets securely.
// Must be called before app is ready.
protocol.registerSchemesAsPrivileged([
    {
        scheme: "inkline-asset",
        privileges: {
            secure: true,
            supportFetchAPI: true,
            bypassCSP: true,
            stream: true,
        },
    },
]);

updateElectronApp();

const dependencies = resolveDependencies();
const appBuilder = new AppBuilder(dependencies);

let loadingWindow: BrowserWindow | null = null;
let setupWindow: BrowserWindow | null = null;

const EMPTY_STARTUP_INTEGRITY_STATUS: StartupIntegrityStatus = {
    state: "idle",
    repairedTargets: [],
    errors: [],
};

let startupIntegrityStatus: StartupIntegrityStatus = {
    ...EMPTY_STARTUP_INTEGRITY_STATUS,
};
let startupIntegrityStarted = false;

const getStartupIntegrityStatus = (): StartupIntegrityStatus => ({
    ...startupIntegrityStatus,
    repairedTargets: [...startupIntegrityStatus.repairedTargets],
    errors: [...startupIntegrityStatus.errors],
});

const broadcastFeatureDownloadProgress = (progress: DownloadProgress): void => {
    const windows = BrowserWindow.getAllWindows();
    for (const win of windows) {
        if (win.isDestroyed()) {
            continue;
        }
        win.webContents.send(
            FEATURE_CHANNELS.FEATURE_DOWNLOAD_PROGRESS,
            progress,
        );
    }
};

const runStartupIntegrityCheck = async (): Promise<void> => {
    if (startupIntegrityStarted) {
        return;
    }

    startupIntegrityStarted = true;
    startupIntegrityStatus = {
        state: "running",
        startedAt: new Date().toISOString(),
        repairedTargets: [],
        errors: [],
    };

    const repairedTargets = new Set<string>();
    const errors: string[] = [];

    const toProgressSender = (
        progress: DownloadProgress,
        source: "setup" | "feature-toggle" | "startup-integrity",
    ): DownloadProgress => ({
        ...progress,
        source,
    });

    const sendStartupProgress = (progress: DownloadProgress): void => {
        broadcastFeatureDownloadProgress(
            toProgressSender(progress, "startup-integrity"),
        );
    };

    const checkModelIntegrity = async (
        modelType: "image" | "audio",
    ): Promise<void> => {
        const downloaded =
            await modelDownloadService.isModelDownloaded(modelType);
        await setupService.markModelDownloaded(modelType, downloaded);
        if (downloaded) {
            return;
        }

        await modelDownloadService.downloadModel(
            modelType,
            sendStartupProgress,
        );
        await setupService.markModelDownloaded(modelType, true);
        repairedTargets.add(modelType);
    };

    const checkLanguageToolIntegrity = async (): Promise<void> => {
        const installed = await modelDownloadService.isLanguageToolInstalled();
        await setupService.markLanguageToolInstalled(installed);

        if (!installed) {
            await modelDownloadService.downloadLanguageTool(
                sendStartupProgress,
            );
            const installedAfterDownload =
                await modelDownloadService.isLanguageToolInstalled();
            await setupService.markLanguageToolInstalled(
                installedAfterDownload,
            );

            if (!installedAfterDownload) {
                throw new Error(
                    "LanguageTool files are still missing after download.",
                );
            }

            repairedTargets.add("languagetool");
        }

        // LanguageTool service is initialized once during early startup and may
        // still be unavailable even after files are repaired. Force a restart
        // so grammar checks become available immediately.
        await languageToolService.restart();

        if (!languageToolService.isUsingLocalServer()) {
            throw new Error(
                "LanguageTool server did not become ready after restart.",
            );
        }
    };

    try {
        const config = await setupService.getConfig();
        const imageEnabled = config.features.imageGeneration;
        const audioEnabled = config.features.audioGeneration;
        const isWindows = process.platform === "win32";
        const localAiEnabled = imageEnabled || audioEnabled;
        const shouldCheckLocalAi = isWindows && localAiEnabled;

        try {
            await checkLanguageToolIntegrity();
        } catch (error) {
            logger.error(
                "[StartupIntegrity] LanguageTool repair failed",
                error,
            );
            errors.push("LanguageTool");
        }

        if (!shouldCheckLocalAi) {
            const [comfyInstalled, imageDownloaded, audioDownloaded] =
                await Promise.all([
                    modelDownloadService.isComfyUIInstalled(),
                    modelDownloadService.isModelDownloaded("image"),
                    modelDownloadService.isModelDownloaded("audio"),
                ]);

            await setupService.markComfyUIInstalled(comfyInstalled);
            await setupService.markModelDownloaded("image", imageDownloaded);
            await setupService.markModelDownloaded("audio", audioDownloaded);

            startupIntegrityStatus = {
                state: errors.length > 0 ? "error" : "completed",
                startedAt: startupIntegrityStatus.startedAt,
                completedAt: new Date().toISOString(),
                repairedTargets: Array.from(repairedTargets),
                errors,
            };
            return;
        }

        try {
            const comfyInstalled =
                await modelDownloadService.isComfyUIInstalled();
            await setupService.markComfyUIInstalled(comfyInstalled);

            if (!comfyInstalled) {
                await modelDownloadService.downloadComfyUI(sendStartupProgress);
                await setupService.markComfyUIInstalled(true);
                repairedTargets.add("comfyui");
            }
        } catch (error) {
            logger.error("[StartupIntegrity] ComfyUI repair failed", error);
            errors.push("ComfyUI");
        }

        if (imageEnabled) {
            try {
                await checkModelIntegrity("image");
            } catch (error) {
                logger.error(
                    "[StartupIntegrity] Image model repair failed",
                    error,
                );
                errors.push("Image model");
            }
        }

        if (audioEnabled) {
            try {
                await checkModelIntegrity("audio");
            } catch (error) {
                logger.error(
                    "[StartupIntegrity] Audio model repair failed",
                    error,
                );
                errors.push("Audio model");
            }
        }

        const enabledModels: ("image" | "audio")[] = [];
        if (imageEnabled) {
            enabledModels.push("image");
        }
        if (audioEnabled) {
            enabledModels.push("audio");
        }

        if (enabledModels.length > 0) {
            const restoredWorkflows =
                await modelDownloadService.ensureWorkflowsInstalled(
                    enabledModels,
                );

            for (const modelType of restoredWorkflows) {
                repairedTargets.add(
                    modelType === "image" ? "imageWorkflow" : "audioWorkflow",
                );
            }
        }
    } catch (error) {
        logger.error("[StartupIntegrity] Integrity run failed", error);
        errors.push("Startup integrity check");
    }

    startupIntegrityStatus = {
        state: errors.length > 0 ? "error" : "completed",
        startedAt: startupIntegrityStatus.startedAt,
        completedAt: new Date().toISOString(),
        repairedTargets: Array.from(repairedTargets),
        errors,
    };
};

const createLoadingWindow = (): void => {
    loadingWindow = new BrowserWindow({
        width: 300,
        height: 200,
        frame: false,
        transparent: false,
        alwaysOnTop: true,
        resizable: false,
        backgroundColor: "#1e1e1e",
        webPreferences: {
            nodeIntegration: false,
            contextIsolation: true,
            preload: LOADING_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    loadingWindow.loadURL(LOADING_WINDOW_WEBPACK_ENTRY);
};

const createSetupWindow = (): Promise<void> => {
    return new Promise((resolve) => {
        setupWindow = new BrowserWindow({
            width: 600,
            height: 700,
            frame: false,
            resizable: false,
            center: true,
            backgroundColor: "#222324",
            webPreferences: {
                nodeIntegration: false,
                contextIsolation: true,
                preload: SETUP_WINDOW_PRELOAD_WEBPACK_ENTRY,
            },
        });

        setupWindow.loadURL(SETUP_WINDOW_WEBPACK_ENTRY);

        // Setup IPC handlers for this window
        setupSetupIpcHandlers(resolve);

        // Cancel any in-progress AI downloads when window is closing
        // Don't cancel LanguageTool - it downloads in background and should complete
        // Close window when requested from renderer (frameless window close button)
        ipcMain.on(SETUP_CHANNELS.CLOSE_WINDOW, () => {
            setupWindow?.close();
        });

        setupWindow.on("close", () => {
            modelDownloadService.cancelDownload("comfyui");
            modelDownloadService.cancelDownload("image");
            modelDownloadService.cancelDownload("audio");
        });

        setupWindow.on("closed", () => {
            setupWindow = null;
        });
    });
};

const setupSetupIpcHandlers = (onComplete: () => void): void => {
    // Complete setup and launch main app
    ipcMain.handle(
        SETUP_CHANNELS.COMPLETE_SETUP,
        async (
            _event,
            config: {
                features: {
                    aiChat: boolean;
                    imageGeneration: boolean;
                    audioGeneration: boolean;
                };
                theme: { colorScheme: "dark" | "light"; accentColor: string };
            },
        ) => {
            await setupService.saveConfig({
                setupCompleted: true,
                features: config.features,
                theme: config.theme,
            });

            if (setupWindow) {
                setupWindow.close();
                setupWindow = null;
            }

            onComplete();
        },
    );

    // Check platform for Windows-only features
    ipcMain.handle(SETUP_CHANNELS.CHECK_PLATFORM, async () => {
        return {
            platform: process.platform,
            isWindows: process.platform === "win32",
        };
    });

    // Check if ComfyUI is installed
    ipcMain.handle(SETUP_CHANNELS.CHECK_COMFYUI_STATUS, async () => {
        const installed = await modelDownloadService.isComfyUIInstalled();
        return { installed };
    });

    // Check if LanguageTool is installed
    ipcMain.handle(SETUP_CHANNELS.CHECK_LANGUAGETOOL_STATUS, async () => {
        const installed = await modelDownloadService.isLanguageToolInstalled();
        return { installed };
    });

    // Start downloads (ComfyUI + models + LanguageTool)
    ipcMain.handle(
        SETUP_CHANNELS.START_DOWNLOADS,
        async (
            _event,
            request: {
                comfyui: boolean;
                image: boolean;
                audio: boolean;
                languagetool: boolean;
            },
        ) => {
            const sendProgress = (progress: DownloadProgress) => {
                if (setupWindow && !setupWindow.isDestroyed()) {
                    setupWindow.webContents.send(
                        SETUP_CHANNELS.DOWNLOAD_PROGRESS,
                        {
                            ...progress,
                            source: "setup",
                        },
                    );
                }
            };

            // Download ComfyUI first if requested
            if (request.comfyui) {
                try {
                    await modelDownloadService.downloadComfyUI(sendProgress);
                    await setupService.markComfyUIInstalled(true);
                } catch (err) {
                    logger.error("ComfyUI download failed", err);
                    // If ComfyUI fails, we can't proceed with model downloads
                    return;
                }
            }

            // Then download models in parallel
            const modelDownloads: Promise<void>[] = [];

            if (request.image) {
                modelDownloads.push(
                    modelDownloadService
                        .downloadModel("image", sendProgress)
                        .then(() =>
                            setupService.markModelDownloaded("image", true),
                        )
                        .catch((err) => {
                            logger.error("Image model download failed", err);
                        }),
                );
            }

            if (request.audio) {
                modelDownloads.push(
                    modelDownloadService
                        .downloadModel("audio", sendProgress)
                        .then(() =>
                            setupService.markModelDownloaded("audio", true),
                        )
                        .catch((err) => {
                            logger.error("Audio model download failed", err);
                        }),
                );
            }

            await Promise.all(modelDownloads);

            // Download LanguageTool (Java JRE + server) if requested
            // This runs after models since it's independent
            if (request.languagetool) {
                try {
                    await modelDownloadService.downloadLanguageTool(
                        sendProgress,
                    );
                    await setupService.markLanguageToolInstalled(true);
                } catch (err) {
                    logger.error("LanguageTool download failed", err);
                    // Non-fatal - grammar checks remain unavailable until install succeeds
                }
            }
        },
    );

    // Cancel downloads
    ipcMain.handle(
        SETUP_CHANNELS.CANCEL_DOWNLOADS,
        async (
            _,
            types?: ("comfyui" | "image" | "audio" | "languagetool")[],
        ) => {
            if (types && types.length > 0) {
                // Cancel only specific download types
                for (const type of types) {
                    modelDownloadService.cancelDownload(type);
                }
            } else {
                // Cancel all if no types specified
                modelDownloadService.cancelAllDownloads();
            }
        },
    );

    // Check model status
    ipcMain.handle(SETUP_CHANNELS.CHECK_MODEL_STATUS, async () => {
        const [imageDownloaded, audioDownloaded] = await Promise.all([
            modelDownloadService.isModelDownloaded("image"),
            modelDownloadService.isModelDownloaded("audio"),
        ]);
        return { image: imageDownloaded, audio: audioDownloaded };
    });
};

// ──────────────────────────────────────────────────────────────
// Feature management from the main renderer (Settings screen)
// ──────────────────────────────────────────────────────────────

const setupFeatureIpcHandlers = (): void => {
    // Return the current feature config + download status
    ipcMain.handle(FEATURE_CHANNELS.GET_FEATURE_CONFIG, async () => {
        const config = await setupService.getConfig();
        const [imageDownloaded, audioDownloaded, comfyInstalled] =
            await Promise.all([
                modelDownloadService.isModelDownloaded("image"),
                modelDownloadService.isModelDownloaded("audio"),
                modelDownloadService.isComfyUIInstalled(),
            ]);

        return {
            features: config.features,
            modelsDownloaded: {
                image: imageDownloaded,
                audio: audioDownloaded,
            },
            comfyuiInstalled: comfyInstalled,
            isWindows: process.platform === "win32",
            startupIntegrity: getStartupIntegrityStatus(),
        };
    });

    // Enable a local AI feature – triggers downloads in background and
    // sends progress back to the calling window via FEATURE_DOWNLOAD_PROGRESS.
    ipcMain.handle(
        FEATURE_CHANNELS.ENABLE_FEATURE,
        async (event, feature: FeatureKind) => {
            const senderWindow = BrowserWindow.fromWebContents(event.sender);

            const sendProgress = (progress: DownloadProgress) => {
                if (senderWindow && !senderWindow.isDestroyed()) {
                    senderWindow.webContents.send(
                        FEATURE_CHANNELS.FEATURE_DOWNLOAD_PROGRESS,
                        {
                            ...progress,
                            source: "feature-toggle",
                        },
                    );
                }
            };

            // Persist the feature flag immediately
            await setupService.updateFeatures({ [feature]: true });

            const modelType: "image" | "audio" =
                feature === "imageGeneration" ? "image" : "audio";

            // Ensure ComfyUI is installed first
            const comfyInstalled =
                await modelDownloadService.isComfyUIInstalled();
            if (!comfyInstalled) {
                try {
                    await modelDownloadService.downloadComfyUI(sendProgress);
                    await setupService.markComfyUIInstalled(true);
                } catch (err) {
                    logger.error("[Features] ComfyUI download failed", err);
                    // Revert feature flag on failure
                    await setupService.updateFeatures({ [feature]: false });
                    throw err;
                }
            }

            // Download the model
            try {
                await modelDownloadService.downloadModel(
                    modelType,
                    sendProgress,
                );
                await setupService.markModelDownloaded(modelType, true);
            } catch (err) {
                logger.error(
                    `[Features] ${modelType} model download failed`,
                    err,
                );
                // Revert feature flag on failure
                await setupService.updateFeatures({ [feature]: false });
                throw err;
            }
        },
    );

    // Disable a local AI feature – deletes its model (and ComfyUI if neither
    // image nor audio remain).
    ipcMain.handle(
        FEATURE_CHANNELS.DISABLE_FEATURE,
        async (_event, feature: FeatureKind) => {
            await setupService.updateFeatures({ [feature]: false });

            const modelType: "image" | "audio" =
                feature === "imageGeneration" ? "image" : "audio";

            // Delete the model file
            await modelDownloadService.deleteModel(modelType);
            await setupService.markModelDownloaded(modelType, false);

            // Check if the *other* local AI feature is still enabled
            const config = await setupService.getConfig();
            const otherEnabled =
                feature === "imageGeneration"
                    ? config.features.audioGeneration
                    : config.features.imageGeneration;

            // If neither feature needs ComfyUI, delete it
            if (!otherEnabled) {
                await modelDownloadService.deleteComfyUI();
                await setupService.markComfyUIInstalled(false);
            }
        },
    );

    // Cancel a feature download in progress
    ipcMain.handle(
        FEATURE_CHANNELS.CANCEL_FEATURE_DOWNLOAD,
        async (_event, feature: FeatureKind) => {
            const modelType: "image" | "audio" =
                feature === "imageGeneration" ? "image" : "audio";
            modelDownloadService.cancelDownload(modelType);
            // Also revert the feature flag
            await setupService.updateFeatures({ [feature]: false });
        },
    );
};

const createWindow = (): void => {
    const mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        minWidth: 1200,
        show: false,
        transparent: false,
        vibrancy: "under-window",
        visualEffectState: "active",
        titleBarStyle: process.platform === "darwin" ? "hiddenInset" : "hidden",
        ...(process.platform !== "darwin"
            ? {
                  titleBarOverlay: {
                      // Keep this aligned with renderer CSS variables defaults.
                      // Renderer reserves 1px for the divider to show under native window controls.
                      height: 35,
                      // Keep this aligned with renderer CSS variables defaults.
                      // Renderer will override dynamically via IPC when the user changes theme.
                      color: "#222324",
                      symbolColor: "#f6f7fb",
                  },
              }
            : {}),
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    if (!app.isPackaged) {
        mainWindow.webContents.openDevTools({ mode: "detach" });
    }

    // Intercept window.open (e.g. link clicks) and open in the default browser
    mainWindow.webContents.setWindowOpenHandler(({ url }) => {
        if (url.startsWith("https://") || url.startsWith("http://")) {
            shell.openExternal(url);
        }
        return { action: "deny" };
    });

    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
    mainWindow.maximize();
    mainWindow.show();
};

const setupContextMenu = (): void => {
    ipcMain.on("ui:show-context-menu", (event, type, data) => {
        const template: MenuItemConstructorOptions[] = [];

        if (type === "editor") {
            template.push(
                { role: "undo" },
                { role: "redo" },
                { type: "separator" },
                { role: "cut" },
                { role: "copy" },
                { role: "paste" },
                { type: "separator" },
                { role: "selectAll" },
                { type: "separator" },
                {
                    label: "Add Comment",
                    click: () => {
                        event.sender.send("context-menu-command", {
                            command: "add-comment",
                            data,
                        });
                    },
                },
            );
        } else if (type === "binder_chapter") {
            template.push(
                {
                    label: "Rename",
                    click: () => {
                        event.sender.send("context-menu-command", {
                            command: "rename",
                            data,
                        });
                    },
                },
                {
                    label: "Delete",
                    click: () => {
                        event.sender.send("context-menu-command", {
                            command: "delete",
                            data,
                        });
                    },
                },
            );
        } else if (type === "binder_project") {
            template.push({
                label: "Close Project",
                click: () => {
                    event.sender.send("context-menu-command", {
                        command: "close-project",
                        data,
                    });
                },
            });
        }

        if (template.length > 0) {
            const menu = Menu.buildFromTemplate(template);
            menu.popup({
                window:
                    BrowserWindow.fromWebContents(event.sender) || undefined,
            });
        }
    });
};

const bootstrap = async (): Promise<void> => {
    // Register the custom protocol handler first.
    // This handles inkline-asset://local/assets/project/xxx/image.jpg URLs
    protocol.handle("inkline-asset", (request) => {
        // URL format: inkline-asset://local/assets/project/xxx/image.jpg
        // host = "local", pathname = "/assets/project/xxx/image.jpg"
        const url = new URL(request.url);
        const relativePath = decodeURIComponent(url.pathname).replace(
            /^\//,
            "",
        );
        const basePath = fileSystemService.getBasePath();
        const filePath = path.join(basePath, relativePath);

        // Security check: Ensure the resolved path is still within the base path
        if (!filePath.startsWith(basePath)) {
            logger.error(
                `[Security] Blocked path traversal attempt: ${relativePath}`,
            );
            return new Response("Access Denied", { status: 403 });
        }

        // Use pathToFileURL for proper cross-platform file URL conversion
        return net.fetch(pathToFileURL(filePath).toString());
    });

    // Check if this is a first-time run
    // Use --force-setup flag to force the setup wizard (for testing)
    const forceSetup = app.commandLine.hasSwitch("force-setup");
    const isFirstRun = forceSetup || (await setupService.isFirstRun());

    if (forceSetup) {
        logger.info("Force setup flag detected - showing setup wizard");
    }

    if (isFirstRun) {
        // Show setup wizard and wait for completion
        await createSetupWindow();
    }

    createLoadingWindow();

    setupContextMenu();
    setupFeatureIpcHandlers();

    await appBuilder.build();

    const comfyService = dependencies.services.audioGeneration;
    if (comfyService && typeof comfyService.waitForReady === "function") {
        try {
            await comfyService.waitForReady();
        } catch (error) {
            logger.error("Failed to start ComfyUI service", error);
        }
    }

    // Initialize LanguageTool local server
    try {
        await languageToolService.waitForReady();
        if (languageToolService.isUsingLocalServer()) {
            logger.success("LanguageTool ready - using local server");
        } else {
            logger.warn("LanguageTool local server unavailable");
        }
    } catch (error) {
        logger.error("Failed to initialize LanguageTool service", error);
    }

    if (loadingWindow) {
        loadingWindow.close();
        loadingWindow = null;
    }

    createWindow();

    setTimeout(() => {
        void runStartupIntegrityCheck();
    }, 1200);
};

app.whenReady()
    .then(() => bootstrap())
    .catch((error) => {
        logger.error("Failed to bootstrap application", error);
        app.quit();
    });

ipcMain.handle(
    "window:setTitleBarOverlay",
    (
        event,
        overlay: {
            color: string;
            symbolColor?: string;
            height?: number;
        },
    ) => {
        if (process.platform === "darwin") {
            return;
        }

        try {
            if (event.sender.isDestroyed()) {
                return;
            }

            const win = BrowserWindow.fromWebContents(event.sender);
            if (!win || win.isDestroyed()) {
                return;
            }

            const setOverlay = (
                win as unknown as { setTitleBarOverlay?: (o: unknown) => void }
            ).setTitleBarOverlay;
            if (typeof setOverlay !== "function") {
                return;
            }

            setOverlay.call(win, overlay);
        } catch (error) {
            logger.warn(
                "Failed to set title bar overlay (window may be closed)",
                error,
            );
        }
    },
);

// LanguageTool IPC handlers - all HTTP calls are made from main process to avoid CORS
ipcMain.handle(
    "languageTool:checkGrammar",
    async (_event, request: { text: string; language: string }) => {
        return languageToolService.checkGrammar(request);
    },
);

ipcMain.handle("languageTool:isUsingLocalServer", async () => {
    return languageToolService.isUsingLocalServer();
});

// Native file dialog for export
ipcMain.handle(
    "dialog:showSaveDialog",
    async (
        event,
        options: {
            title?: string;
            defaultPath?: string;
            filters?: { name: string; extensions: string[] }[];
        },
    ) => {
        const win = BrowserWindow.fromWebContents(event.sender);
        const result = win
            ? await dialog.showSaveDialog(win, {
                  title: options.title,
                  defaultPath: options.defaultPath,
                  filters: options.filters,
              })
            : await dialog.showSaveDialog({
                  title: options.title,
                  defaultPath: options.defaultPath,
                  filters: options.filters,
              });
        return result;
    },
);

// Native file dialog for import
ipcMain.handle(
    "dialog:showOpenDialog",
    async (
        event,
        options: {
            title?: string;
            filters?: { name: string; extensions: string[] }[];
            properties?: string[];
        },
    ) => {
        const win = BrowserWindow.fromWebContents(event.sender);
        const dialogOptions = {
            title: options.title,
            filters: options.filters,
            properties: (options.properties ?? ["openFile"]) as (
                | "openFile"
                | "openDirectory"
                | "multiSelections"
            )[],
        };
        const result = win
            ? await dialog.showOpenDialog(win, dialogOptions)
            : await dialog.showOpenDialog(dialogOptions);
        return result;
    },
);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

// Cleanup child processes before quitting to prevent orphan processes
app.on("before-quit", async () => {
    logger.info("Cleaning up before quit");

    // Stop sync service (clears intervals and realtime subscriptions)
    dependencies.syncService.stopAutoSync("shutdown");

    // Shutdown ComfyUI server (cast to access implementation-specific method)
    const comfyService = dependencies.services.audioGeneration as unknown as {
        shutdown?: () => void;
    };
    if (comfyService && typeof comfyService.shutdown === "function") {
        comfyService.shutdown();
    }

    // Shutdown LanguageTool server
    await languageToolService.shutdown();

    logger.success("Cleanup complete");
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});
