import "dotenv/config";
import { app, BrowserWindow } from "electron";
import { AppBuilder } from "./AppBuilder";
import { resolveDependencies } from "./dependencies";
import { ComfyAssetGenerationService } from "../@infrastructure/ai/ComfyAssetGenerationService";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
    app.quit();
}

const dependencies = resolveDependencies();
const appBuilder = new AppBuilder(dependencies);

let loadingWindow: BrowserWindow | null = null;

const createLoadingWindow = (): void => {
    loadingWindow = new BrowserWindow({
        width: 400,
        height: 200,
        frame: false,
        transparent: false,
        alwaysOnTop: true,
        resizable: false,
        webPreferences: {
            nodeIntegration: false,
            contextIsolation: true,
        },
    });

    loadingWindow.loadURL(
        `data:text/html;charset=utf-8,
        <html>
            <body style="font-family: sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; background-color: #1e1e1e; color: #e0e0e0; flex-direction: column; margin: 0;">
                <h2 style="margin-bottom: 10px;">Inkline</h2>
                <div style="font-size: 14px; color: #aaaaaa;">Starting AI Services...</div>
                <div style="margin-top: 20px; width: 200px; height: 4px; background: #333; border-radius: 2px; overflow: hidden;">
                    <div style="width: 100%; height: 100%; background: #4a90e2; animation: loading 2s infinite ease-in-out;"></div>
                </div>
                <style>
                    @keyframes loading {
                        0% { transform: translateX(-100%); }
                        100% { transform: translateX(100%); }
                    }
                </style>
            </body>
        </html>`
    );
};

const createWindow = (): void => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        show: false,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    mainWindow.maximize();
    mainWindow.show();

    // Open the DevTools.
    mainWindow.webContents.openDevTools({
        mode: "detach",
    });
};

const bootstrap = async (): Promise<void> => {
    createLoadingWindow();

    await appBuilder.build();

    const comfyService = dependencies.services
        .audioGeneration as ComfyAssetGenerationService;
    if (comfyService && typeof comfyService.waitForReady === "function") {
        try {
            await comfyService.waitForReady();
        } catch (error) {
            console.error("Failed to start ComfyUI service:", error);
        }
    }

    if (loadingWindow) {
        loadingWindow.close();
        loadingWindow = null;
    }

    createWindow();
};

app.whenReady()
    .then(() => bootstrap())
    .catch((error) => {
        console.error("Failed to bootstrap application", error);
        app.quit();
    });

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
