import "dotenv/config";
import {
    app,
    BrowserWindow,
    ipcMain,
    Menu,
    MenuItemConstructorOptions,
} from "electron";
import { AppBuilder } from "./AppBuilder";
import { resolveDependencies } from "./dependencies";
import { ComfyAssetGenerationService } from "../@infrastructure/ai/ComfyAssetGenerationService";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const LOADING_WINDOW_WEBPACK_ENTRY: string;
declare const LOADING_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
    app.quit();
}

const dependencies = resolveDependencies();
const appBuilder = new AppBuilder(dependencies);

/*
dependencies.syncService.on("update-available", (payload) => {
    BrowserWindow.getAllWindows().forEach((win) => {
        if (!win.isDestroyed()) {
            win.webContents.send("manuscript:updateAvailable", payload);
        }
    });
});
*/

let loadingWindow: BrowserWindow | null = null;

const createLoadingWindow = (): void => {
    loadingWindow = new BrowserWindow({
        width: 300,
        height: 200,
        frame: false,
        transparent: false,
        alwaysOnTop: true,
        resizable: false,
        backgroundColor: "#1e1e1e",
        webPreferences: {
            nodeIntegration: false,
            contextIsolation: true,
            preload: LOADING_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    loadingWindow.loadURL(LOADING_WINDOW_WEBPACK_ENTRY);
};

const createWindow = (): void => {
    const mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        minWidth: 1200,
        show: false,
        transparent: false,
        vibrancy: "under-window",
        visualEffectState: "active",
        titleBarStyle: process.platform === "darwin" ? "hiddenInset" : "hidden",
        ...(process.platform !== "darwin"
            ? {
                  titleBarOverlay: {
                      // Keep this aligned with renderer CSS variables defaults.
                      // Renderer reserves 1px for the divider to show under native window controls.
                      height: 35,
                      // Keep this aligned with renderer CSS variables defaults.
                      // Renderer will override dynamically via IPC when the user changes theme.
                      color: "#222324",
                      symbolColor: "#f6f7fb",
                  },
              }
            : {}),
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    if (!app.isPackaged) {
        mainWindow.webContents.openDevTools({ mode: "detach" });
    }

    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
    mainWindow.maximize();
    mainWindow.show();
};

const setupContextMenu = (): void => {
    ipcMain.on("ui:show-context-menu", (event, type, data) => {
        const template: MenuItemConstructorOptions[] = [];

        if (type === "editor") {
            template.push(
                { role: "undo" },
                { role: "redo" },
                { type: "separator" },
                { role: "cut" },
                { role: "copy" },
                { role: "paste" },
                { type: "separator" },
                { role: "selectAll" }
            );
        } else if (type === "binder_chapter") {
            template.push(
                {
                    label: "Rename",
                    click: () => {
                        event.sender.send("context-menu-command", {
                            command: "rename",
                            data,
                        });
                    },
                },
                {
                    label: "Delete",
                    click: () => {
                        event.sender.send("context-menu-command", {
                            command: "delete",
                            data,
                        });
                    },
                }
            );
        } else if (type === "binder_project") {
            template.push({
                label: "Close Project",
                click: () => {
                    event.sender.send("context-menu-command", {
                        command: "close-project",
                        data,
                    });
                },
            });
        }

        if (template.length > 0) {
            const menu = Menu.buildFromTemplate(template);
            menu.popup({
                window:
                    BrowserWindow.fromWebContents(event.sender) || undefined,
            });
        }
    });
};

const bootstrap = async (): Promise<void> => {
    createLoadingWindow();

    setupContextMenu();

    await appBuilder.build();

    const comfyService = dependencies.services
        .audioGeneration as ComfyAssetGenerationService;
    if (comfyService && typeof comfyService.waitForReady === "function") {
        try {
            await comfyService.waitForReady();
        } catch (error) {
            console.error("Failed to start ComfyUI service:", error);
        }
    }

    if (loadingWindow) {
        loadingWindow.close();
        loadingWindow = null;
    }

    createWindow();
};

app.whenReady()
    .then(() => bootstrap())
    .catch((error) => {
        console.error("Failed to bootstrap application", error);
        app.quit();
    });

ipcMain.handle(
    "window:setTitleBarOverlay",
    (
        event,
        overlay: {
            color: string;
            symbolColor?: string;
            height?: number;
        }
    ) => {
        if (process.platform === "darwin") {
            return;
        }

        const win = BrowserWindow.fromWebContents(event.sender);
        if (!win) {
            return;
        }

        const setOverlay = (
            win as unknown as { setTitleBarOverlay?: (o: unknown) => void }
        ).setTitleBarOverlay;
        if (typeof setOverlay !== "function") {
            return;
        }

        setOverlay(overlay);
    }
);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
